name: Build and Output Executable

on:
  push:
    branches:
      - feat-gh-action-build
  pull_request:
    branches:
      - feat-gh-action-build

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Build project
        run: xcodebuild -project IpInfo.xcodeproj -scheme IpInfo -configuration Release

      - name: List output directory contents
        run: ls -la output/

      - name: Save executable
        uses: actions/upload-artifact@v4
        with:
          name: IpInfo
          path: IpInfo/output/IpInfo.app
